### ISSUE TITLE
style.css Bug Report

### ISSUE THREAD

**Issue by flavio23s** [flavio23s/desenvolvedor#2]
The code you provided is a CSS (Cascading Style Sheets) style block, not a programming language like JavaScript or Python. CSS is used to style the layout and appearance of HTML elements.

I have reviewed the CSS code, and I didn't find any syntax errors or bugs. However, I noticed that some of the CSS rules are missing the "selector" part, which should be defined before the "{" character. Here are the corrected CSS rules:

```css
body {
    font-family: Arial, sans-serif;
    margin: 20px;
    padding: 0;
    background: #f8f9fa;
    color: #212529;
}

.container {
    max-width: 800px;
    margin: auto;
    background: #fff;
    padding: 20px;
    border-radius: 5px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, .1);
}

h1, h2, h3 {
    color: #007bff;
}

p {
    line-height: 1.6;
}

ul {
    margin-left: 20px;
}

a {
    color: #007bff;
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}
```

By adding the missing selectors, the CSS code will now correctly apply the styles to the corresponding HTML elements.
