### ISSUE TITLE
regular.css Bug Report

### ISSUE THREAD

**Issue by flavio23s** [flavio23s/desenvolvedor#3]
Based on the provided code, I can see a potential issue related to the `@font-face` rule. The issue is that the `font-display` property is set to `block`, which can cause a flash of unstyled text (FOUT) to appear on the page while the font is loading. This can be frustrating for users, especially on slow connections.

To improve the user experience, you can consider setting the `font-display` property to a more appropriate value, such as `swap`. This will ensure that the browser uses a fallback font while the custom font is loading, and then swaps in the custom font once it has finished loading.

Here's an example of how you can modify the `@font-face` rule to use the `swap` value for `font-display`:

```css
@font-face {
  font-family: 'Font Awesome 6 Free';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url("../webfonts/fa-regular-400.woff2") format("woff2"), url("../webfonts/fa-regular-400.ttf") format("truetype");
}
```

Other than this, I don't see any other bugs in the code you provided. However, it's always a good idea to thoroughly test your code in different browsers and devices to ensure that it works as expected.
